# Generated by Django 6.0.1 on 2026-01-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0002_alter_author_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="purchaseDate",
        ),
    ]
