# Generated by Django 6.0.1 on 2026-02-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0003_remove_book_purchasedate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                help_text="Select authors for this book",
                related_name="books",
                to="booklibrary.author",
            ),
        ),
    ]
