# Generated by Django 6.0.1 on 2026-03-06 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0004_alter_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="contentType",
            field=models.TextField(
                blank=True,
                help_text="EBOK for ebook, PHY for physical",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Title must be at least 1 character"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                help_text="Enter a location where the book is stored", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(
                default="None",
                help_text="Enter a series name that the book is part of",
                max_length=200,
            ),
        ),
    ]
