# Generated by Django 6.0.1 on 2026-03-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booklibrary", "0005_alter_book_contenttype_alter_book_title_and_more"),
        ("booklibrary", "0005_bookinstance_status"),
    ]

    operations = []
